### ISSUE TITLE
#issue001. API 요청 바인딩 예외 처리 관련된 질문건입니다.

### ISSUE THREAD

**Issue by jojiapp** [spring-React-blog/blog-server-jh#12]
API 요청 시 바인딩 예외가 발생하면 BindingError 객체에 실패 필드에 대한 정보가 담기게 됩니다.

```
@Getter
@AllArgsConstructor
class RequestDTO {

    @Valid
    private Title title;
}
```

```
@AllArgsConstructor
public class Title {

    @NotBlank
    private String title;

    @JsonValue
    public String getTitle() {
        return title;
    }
}
```

이때, DTO에서 Title 같은 VO 객체를 사용하게 되면 바인딩 실패 필드 명이 `title.title`이 됩니다.

요청을 보낼때는 `{"title": "제목"}`으로 보내면 바인딩이 되는데, 바인딩 실패 시 필드는 `title.title`이 된다는 점입니다.
실패 시 필드도 `title` 이 되어야 맞는거 같은데 이렇게 할려면 어떻게 하는게 좋을지 궁금합니다.

**Comment by ilgolf** [comment]
가장 좋은 방법은 DTO는 String Type으로 가져가는 것 입니다. 그렇게 되면 VO에서 공통으로 validation처리는 안되겠지만 아마 현재 겪는 문제는 발생하지 않을 것입니다. 하지만 DTO 내에서 뭔가 추가적인 mapping 과정이 추가될 것 같습니다.

**Comment by jojiapp** [comment]
말씀해주신대로 요청 DTO 정도는 String 타입으로 가져가는것이 좋을것 같네요 감사합니다 :)
